### ISSUE TITLE
null version value is ignored in shadowJar configuration

### ISSUE THREAD

**Issue by alexeyOnGitHub** [GradleUp/shadow#508]
### Shadow Version
5.1.0

### Gradle Version
5.6

### Expected Behavior

I want the final artifact name to not have version number in it, so I am trying this snippet from documentation:
```

shadowJar {
    baseName = 'shadow'
    classifier = null
    version = null
}
```

also tried
```
shadowJar {
    classifier = null
    archiveVersion = null
}

```
### Actual Behavior

"classifier" is removed as expected, but "version" is still added to the final artifact name.

**Comment by Bo98** [comment]
This is caused by a breaking change in https://github.com/gradle/gradle/pull/9776.

It's noted [here](https://docs.gradle.org/current/userguide/upgrading_version_5.html):

> #### Setting Property value to null uses the property convention
>
> Previously, calling Property.set(null) would always reset the value of the property to 'not defined'. Now, the convention that is associated with the property using the convention() method will be used to determine the value of the property.

This is perhaps not very obvious however as `version` is documented as `String` and _not_ `Property<String>`. In Gradle 5.1, `version` was deprecated and replaced by `archiveVersion` which _is_ a `Property<String>`, and internally `version` just maps to `archiveVersion`.

Try use `version = ""` or `archiveVersion.set("")` instead.

[The shadowJar docs](https://imperceptiblethoughts.com/shadow/configuration/#configuring-output-name) will need updating because of this change.

**Comment by anderssv** [comment]
Having same problem. Did not work with setting to blank strings.

**Comment by Goooler** [comment]
Use empty strings instead.
